version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devtriage
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  kafka:
    image: redpandadata/redpanda:v24.1.5
    command: ["redpanda", "start", "--overprovisioned", "--smp", "1", "--memory", "512M", "--reserve-memory", "0M", "--node-id", "0", "--check=false"]
    ports:
      - "9092:9092"
      - "9644:9644"

  backend:
    build: ./packages/backend
    env_file: .env
    depends_on: [db, kafka]
    ports:
      - "3000:3000"

  agent:
    build: ./packages/agent
    env_file: .env
    depends_on: [db, backend]
    ports:
      - "8000:8000"

  frontend:
    build: ./packages/frontend
    env_file: .env
    depends_on: [backend]
    ports:
      - "5173:5173"

volumes:
  dbdata:
